### ISSUE TITLE
Past Messages Always Visible to New User

### ISSUE THREAD

**Issue by geekananya** [LyubomirT/alert-chatroom#10]
Bug:
- This is irrespective of selecting whether to Allow new users to see past messages or not. 
- When the option is enabled, the old messages are rendered twice.

**Comment by LyubomirT** [comment]
Thank you for reporting the issue! I've identified the cause and am now implementing a fix.

**Comment by LyubomirT** [comment]
Monitoring; The implementation has been applied to the source code and the deployed website.

**Comment by geekananya** [comment]
@LyubomirT works fine now, thank you!
