### ISSUE TITLE
📱Fix Mobile UI

### ISSUE THREAD

**Issue by LyubomirT** [LyubomirT/alert-chatroom#11]
Address responsive design issues and optimize user interface elements for mobile devices to improve usability and appearance on smaller screens.

**Comment by GeorgiosDrivas** [comment]
Hello @LyubomirT! I would like to work on this issue, in order to make the app more accessible through mobiles.

**Comment by LyubomirT** [comment]
@GeorgiosDrivas Assigned you to the issue, thanks for considering contributing to this project! Good luck!

**Comment by GeorgiosDrivas** [comment]
Thank you for the opportunity! I will start today, and I will keep you updated throughout the process.

**Comment by GeorgiosDrivas** [comment]
Hello Lyubomir @LyubomirT. I wanted to give you an update before creating a pull request, to avoid changing it later. Below, you will find attached some screenshots of the app after applying css to make it more responsive. Please feel free to highlight any changes you want me to make.

![tablet_1](https://github.com/user-attachments/assets/a8eff989-a6bc-44c5-964c-5d738c59ed09)
![tablet_2](https://github.com/user-attachments/assets/54d22f49-9c04-4002-916f-a5023e910963)
![tablet_3](https://github.com/user-attachments/assets/29139414-7fdf-4486-99a1-0974150fb1f1)
![phone_1](https://github.com/user-attachments/assets/bcc6d8d0-9fc2-4a39-bf3f-8b3fd19913ba)
![phone_2](https://github.com/user-attachments/assets/265837ea-a68e-4191-ae34-ef51a3fe65f4)
![phone_3](https://github.com/user-attachments/assets/a88ce23d-73f3-4817-8733-a0d4c6261ead)

**Comment by LyubomirT** [comment]
Looks great @GeorgiosDrivas! I think we could collapse the part with chatroom controls (image attached) to be a horizontal bar with icons, to preserve vertical space.
<img width="205" alt="image" src="https://github.com/user-attachments/assets/dd589431-a9b9-4d1d-b59a-89bfab3d6dfc">

**Comment by GeorgiosDrivas** [comment]
I believe now it seems prettier, with the horizontal icons you proposed. What do you think?
![Screenshot 2024-08-04 122544](https://github.com/user-attachments/assets/c1ff70e4-3cac-4aee-9e1b-af61989dabcf)

**Comment by LyubomirT** [comment]
I think it looks amazingly well-done, thank you!

**Comment by GeorgiosDrivas** [comment]
One last thing before I create the pull request. I noticed you have seperate css files for each html file. I decided to write the responsive css in the corresponding css file rather than creating a responsive.css file, just to avoid making it more complex. Is it ok with you or should I merge every responsive rule in a single file?

**Comment by LyubomirT** [comment]
Yes, that's actually how it's better in my opinion. I think you should leave it like this.
