### ISSUE TITLE
😉 Add Emoji Reactions to System Messages

### ISSUE THREAD

**Issue by LyubomirT** [LyubomirT/alert-chatroom#2]
System messages (e.g., user join/leave notifications) currently don't support emoji reactions. Adding this feature would make the chat more interactive and consistent with user messages.

**Comment by tinahsr** [comment]
Hey! I would like to work on this issue :)

**Comment by LyubomirT** [comment]
Sure! I'm assigning you to it, thank you for considering contributing to the project!
