### ISSUE TITLE
🌙 Implement Dark Mode

### ISSUE THREAD

**Issue by LyubomirT** [LyubomirT/alert-chatroom#4]
Add a dark mode option for the chat interface to improve user experience in low-light environments and provide a modern aesthetic option.

**Comment by oscarArismendi** [comment]
Hi,

I’m interested in working on this issue. Could you please clarify a couple of things for me?

1. Do you have a color palette or any design images that illustrate how you envision the final look?
2. Would it be possible to use global variables in the CSS to facilitate easier updates in the future?

Thanks!

**Comment by LyubomirT** [comment]
Sure thing, thank you for your interest in contributing to the project!

1. Not really, but I can create one if needed. I think we should stick to the original color scheme, and adapt it to the dark version.
2. Absolutely! I'd be grateful if you could implement global variables, no idea how I missed that while working on this. 😅

Assigning you to the issue. Good luck!

**Comment by oscarArismendi** [comment]
I have advanced in the dark mode, and I would like to know if you like them or if there are any improvements you think could be made.

<p align="center">
<img src="https://github.com/user-attachments/assets/b71e6661-fa48-42b2-b83f-c87ecbd3ce4d">
</p>
<p align="center">Fig.1 Normal chat interaction</p>
<p align="center">
<img src="https://github.com/user-attachments/assets/8693173c-d104-40b9-a49e-9dbb2385ae79">
</p>
<p align="center">Fig.2 Pinned message</p>

**Comment by LyubomirT** [comment]
Looks great so far! If possible, I'd leave all the text white and I'd make the color palette for the chat less green. Also, if possible, please make the chat background dark too.
